<section class="club-section">
    <div class="background-club">

        <div class="creation block">
            <h2>Date de création</h2>
            <p>Club crée en 2018 par Nicolas et Vincent</p>
        </div>
        <div class="participations block">
            <h2>Participations</h2>
            <p>L'équipe participe à différentes compétitions organisés par l'association footfsgt</p>
            <p>
                Nous sommes actuellement inscrit aux championnat départementale de foot à 7.
                Encore en course pour la coupe régionnale.
            </p>
        </div>
    </div>

</section>
