<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" type="image/png" href="<?= $wwwUrl ?>/images/site/logo.png">
    <title>FC BAYER LEVERKUSEC</title>
    <!--icones-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <!-- mon css -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
    <!-- Librairie jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
          integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
          crossorigin="anonymous">
    </script>
    <!-- Librairie jQuery - Slider -->

    <link rel="stylesheet" href="<?= $wwwUrl ?>/FlexSlider/flexslider.css" type="text/css">
    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>

</head>
<body>
<!-- En-tête commune -->
<header>
    <div class="header-top">
        <a class="top-header-logo" href="<?= $requestUrl ?>"><img src="<?= $wwwUrl ?>/images/site/logo-nav.png" alt="logo Bayer leverkusec"></a>
        <a class="h1" href="<?= $requestUrl ?>"><h1>FC BAYER LEVERKUSEC</h1></a>
    </div>
    <div class="header-bottom">
        <div class="background-nav"></div>
        <nav class="menu-nav">
            <ul>
                <li class="li-logo">
                    <a class="bottom-header-logo" href="<?= $requestUrl ?>"><img src="<?= $wwwUrl ?>/images/site/logo.png" alt="logo Bayer leverkusec"></a>
                </li>
                <li>
                    <!-- <i class="fas fa-beer hide"></i> -->
                    <a href="<?= $requestUrl ?>/club"><i class="fas fa-beer hide"></i>LE CLUB<i class="fas fa-beer hide"></i></a>
                    <!-- <i class="fas fa-beer hide"></i> -->
                </li>
                <li>
                    <!-- <i class="fas fa-beer hide"></i> -->
                    <a href="<?= $requestUrl ?>/team"><i class="fas fa-beer hide"></i>L'EQUIPE<i class="fas fa-beer hide"></i></a>
                    <!-- <i class="fas fa-beer hide"></i> -->
                </li>
                <li>
                    <!-- <i class="fas fa-beer hide"></i> -->
                    <a href="<?= $requestUrl ?>/competition"><i class="fas fa-beer hide"></i>COMPETITIONS<i class="fas fa-beer hide"></i></a>
                    <!-- <i class="fas fa-beer hide"></i> -->
                </li>
                <li>
                    <!-- <i class="fas fa-beer hide"></i> -->
                    <a href="<?= $requestUrl ?>/contact"><i class="fas fa-beer hide"></i>CONTACT<i class="fas fa-beer hide"></i></a>
                    <!-- <i class="fas fa-beer hide"></i> -->
                </li>
                <li>
                    <!-- <i class="fas fa-beer hide"></i> -->
                    <a href="<?= $requestUrl ?>/admin"><i class="fas fa-beer hide"></i><i class="fas fa-cogs"></i>  Administrateur<i class="fas fa-beer hide"></i></a>
                    <!-- <i class="fas fa-beer hide"></i> -->
                </li>
            </ul>
        </nav>
    </div>
</header>
<!-- Interface utilisateur -->
<!-- <nav class="user-interface">
    <ul class="link-list">
         Code HTML/PHP à écrire
    </ul>
</nav> -->

<main class="container">
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <nav class="menu-footer">
            <ul>
                <li><a href="#">Sponsors</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
    </nav>
    <p>&copy; 2018 FC Bayer Leverkusec<p>
</footer>

<!-- Code principal JavaScript de l'application -->
    <script type="text/javascript" src="<?= $wwwUrl ?>/js/header.js"></script>
    <script type="text/javascript" src="<?= $wwwUrl ?>/js/adminChampionshipManager.js"></script>
    <script type="text/javascript" src="<?= $wwwUrl ?>/js/adminPostManager.js"></script>
    <script type="text/javascript" src="<?= $wwwUrl ?>/js/adminTeamManager.js"></script>
    <script type="text/javascript" src="<?= $wwwUrl ?>/js/main.js"></script>
    <script src="<?= $wwwUrl ?>/FlexSlider/jquery.flexslider.js"></script>
    <script type="text/javascript" charset="utf-8">
        $('.flexslider').flexslider({

            slideshowSpeed:5000
        });
    </script>
</body>
</html>
