<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" type="image/png" href="<?= $wwwUrl ?>/images/site/logo.png">
    <title>FC BAYER LEVERKUSEC</title>
    <!--icones-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <!-- mon css -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
    <!-- Librairie jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
          integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
          crossorigin="anonymous">
    </script>
    <!-- Librairie jQuery - Slider -->

    <link rel="stylesheet" href="<?= $wwwUrl ?>/FlexSlider/flexslider.css" type="text/css">
    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>

</head>
<body>
<!-- En-tête commune -->
<header>
    <h1><i class="fas fa-beer"></i>FC BAYER LEVERKUSEC<i class="fas fa-beer"></i></h1>
    <img src="<?= $wwwUrl ?>/images/site/logo.png" alt="logo Bayer leverkusec">
    <div class="line-shadow">
    </div>
    <nav class="menu-nav">
        <ul class="container">
            <li>
                <a href="<?= $requestUrl ?>">ACCUEIL</a>
            </li>
            <li>
                <a href="<?= $requestUrl ?>/club">LE CLUB</a>
            </li>
            <li>
                <a href="<?= $requestUrl ?>/team">L'EQUIPE</a>
            </li>
            <li>
                <a href="<?= $requestUrl ?>/competition">CALENDRIERS / CLASSEMENTS</a>
            </li>
            <li>
                <a href="<?= $requestUrl ?>/contact">CONTACT</a>
            </li>
            <li>
                <a href="<?= $requestUrl ?>/admin"><i class="fas fa-cogs"></i>  Administrateur</a>
            </li>
        </ul>
    </nav>
</header>
<!-- Interface utilisateur -->
<nav class="user-interface">
    <ul class="link-list">
        <!-- Code HTML/PHP à écrire -->
    </ul>
</nav>

<main class="container">
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <nav class="menu-footer">
            <ul>
                <li><a href="#">Sponsors</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
    </nav>
    <p>&copy; 2018 FC Bayer Leverkusec<p>
</footer>

<!-- Code principal JavaScript de l'application -->
    <script type="text/javascript" src="<?= $wwwUrl ?>/js/adminChampionshipManager.js"></script>
    <script type="text/javascript" src="<?= $wwwUrl ?>/js/adminPostManager.js"></script>
    <script type="text/javascript" src="<?= $wwwUrl ?>/js/adminTeamManager.js"></script>
    <script type="text/javascript" src="<?= $wwwUrl ?>/js/main.js"></script>
    <script src="<?= $wwwUrl ?>/FlexSlider/jquery.flexslider.js"></script>
    <script type="text/javascript" charset="utf-8">
        $('.flexslider').flexslider({

            slideshowSpeed:5000
        });
    </script>
</body>
</html>
