<nav class="nav-button">
    <ul>
        <li><a href="<?= $requestUrl ?>/admin/post">Gérer les articles</a></li>
        <li><a href="<?= $requestUrl ?>/admin/team">Gérer l'équipe</a></li>
        <li><a href="<?= $requestUrl ?>/admin/competition">Gérer les compétitions</a></li>
    </ul>
</nav>
<nav class="nav-button">
    <ul>
        <li><a href="<?= $requestUrl ?>/admin/competition/championship">Championnat</a></li>
      <!--  <li><a href="<?/*= $requestUrl */?>/admin/competition/cup">Coupe</a></li>
        <li><a href="<?/*= $requestUrl */?>/admin/competition/team">Equipe</a></li>-->
    </ul>
</nav>
