<section>
    <h2>Contactez-nous</h2>
    <fieldset>
        <legend>Envoyer un mail</legend>
        <form action="">
            <div class="field">
                <label for="object">Objet : </label>
                <input type="text" name="object" value="" maxlength="30" required>
            </div>
            <div class="field area">
                <label for="message">Message :</label>
                <textarea name="message" rows="8" cols="80" required></textarea>
            </div>
            <div class="div-button">
                <input type="submit" name="send-message" value="Envoyer">
            </div>
        </form>
    </fieldset>
</section>
